test:
  db_hostname:
  db_username:
  db_password:
  db_name:
  app_hostname:
  app_portname:

  devise_secret_key:
  devise_pepper_hash:
  devise_mailer_from_address:

  hmac_secret:

  github_client_id:
  github_secret_key:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:
  app_hostname:
  app_portname:

  devise_secret_key:
  devise_pepper_hash:
  devise_mailer_from_address:

  hmac_secret:

  github_client_id:
  github_secret_key:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:
  app_hostname:
  app_portname:

  devise_secret_key:
  devise_pepper_hash:
  devise_mailer_from_address:

  hmac_secret:

  github_client_id:
  github_secret_key: