test:
  db_hostname:
  db_username:
  db_password:
  db_name:
  app_hostname:
  app_portname:

  devise_secret_key:
  devise_pepper_hash:
  devise_mailer_from_address:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:
  app_hostname:
  app_portname:

  devise_secret_key:
  devise_pepper_hash:
  devise_mailer_from_address:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:
  app_hostname:
  app_portname:

  devise_secret_key:
  devise_pepper_hash:
  devise_mailer_from_address: